---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: vault
  labels:
    app: vault
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - name: vault
        command: ["vault", "server", "-config", "/config/vault.hcl"]
        image: "vault:1.4.2"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8200
          name: api
        - containerPort: 8201
          name: cluster-address
        lifecycle:
          preStop:
            exec:
              command: [
                "sh", "-c",
                # Introduce a delay to the shutdown sequence to wait for the
                # pod eviction event to propagate.
                "sleep 7",
              ]
        livenessProbe:
          # Alive if Vault is successfully responding to requests
          httpGet:
            path: /v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204&
            port: 8200
            scheme: HTTPS
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          # Ready depends on preference
          httpGet:
            path: /v1/sys/health?standbyok=204&
            port: 8200
            scheme: HTTPS
          initialDelaySeconds: 10
          periodSeconds: 10
        env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: VAULT_CLUSTER_ADDR
            value: "https://$(POD_IP):8201"
          - name: VAULT_LOG_LEVEL
            value: "INFO"
          - name: VAULT_CACERT
            value: "/etc/tls/ca.pem"
          - name: VAULT_CLIENT_CERT
            value: "/etc/tls/vault.pem"
          - name: VAULT_CLIENT_KEY
            value: "/etc/tls/vault-key.pem"
        securityContext:
          readOnlyRootFilesystem: true
          capabilities:
            add:
              - IPC_LOCK
        volumeMounts:
          - name: vault-config
            mountPath: /config
          - name: tls
            mountPath: /etc/tls
        resources: {}
      - name: consul
        image: "consul:1.7.2"
        imagePullPolicy: IfNotPresent
        env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: GOSSIP_ENCRYPTION_KEY
            valueFrom:
              secretKeyRef:
                name: vault
                key: gossip-encryption-key
        args:
          - "agent"
          - "-config-file=/config/consul-vault.hcl"
          - "-encrypt=$(GOSSIP_ENCRYPTION_KEY)"
        volumeMounts:
          - name: consul-config
            mountPath: /config
          - name: tls
            mountPath: /etc/tls
        lifecycle:
          preStop:
            exec:
              command: [
                "sh", "-c",
                # shutdown vault first, then shutdown consul agent
                "sleep 6 && consul leave"
              ]
        resources: {}
      volumes:
        - name: vault-config
          configMap:
            name: vault
        - name: consul-config
          configMap:
            name: consul
        - name: tls
          secret:
            secretName: vault
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - vault
              topologyKey: kubernetes.io/hostname
